// Objective-C API for talking to Hello/src/hello Go package.
//   gobind -lang=objc Hello/src/hello
//
// File is generated by gobind. Do not edit.

#ifndef __Hello_H__
#define __Hello_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull HelloGreetings(NSString* _Nullable name);

#endif
